# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:
- task: katalonTask@1
  inputs:
    version: '8.4.0'
    executeArgs: '-browserType="Chrome" -apiKey=$(apikey)  -retry=0 -statusDelay=15 -testSuitePath="Test Suites/TS_RegressionTest"  --config -webui.autoUpdateDrivers=true -adoTestRunName="TS_RegressionTest"  -adoPlanId=858'
    #-testSuiteCollectionPath
    #--info -adoReleaseDefID=1
    #-adoPlanId=842
 
