<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Rare find_FMP-target</name>
   <tag></tag>
   <elementGuidId>a8d93dc6-a737-4739-9348-358e57b41ac4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>picture > #FMP-target</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='FMP-target']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0a8d59a7-74a0-4cb3-a8b1-e79711dedbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>_6tbg2q</value>
      <webElementGuid>9be0c6af-13ef-44cc-8485-d0ab7d927a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>49cdffcd-8f9b-4faa-932c-603201b7bad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Image 1</value>
      <webElementGuid>5205c09d-fb7a-4da2-9227-be61cbd887e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>elementtiming</name>
      <type>Main</type>
      <value>LCP-target</value>
      <webElementGuid>e816cf35-0e35-4d9c-a52a-8ef3e3bdcb29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fetchpriority</name>
      <type>Main</type>
      <value>high</value>
      <webElementGuid>febf4ff7-7e90-465b-939a-d6eb4972a391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FMP-target</value>
      <webElementGuid>cf90870b-09a3-44ae-b13f-2c3c99f4abff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>eager</value>
      <webElementGuid>303c7c1a-1130-4b65-bfa7-99dde1931236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://a0.muscache.com/im/pictures/af870499-6c81-4b77-b283-c861cc7c93ed.jpg?im_w=720</value>
      <webElementGuid>0c481493-524b-43e4-965c-da6985f8be04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original-uri</name>
      <type>Main</type>
      <value>https://a0.muscache.com/im/pictures/af870499-6c81-4b77-b283-c861cc7c93ed.jpg?im_w=720</value>
      <webElementGuid>b1e0cc6f-4824-4086-87ae-0357359fd085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;site-content&quot;)/div[@class=&quot;f7uhbhg dir dir-ltr&quot;]/div[4]/div[1]/div[@class=&quot;_le6wlg&quot;]/div[@class=&quot;plmw1e5 mq5rv0q dir dir-ltr&quot;]/div[1]/div[@class=&quot;_11ry7lz&quot;]/div[@class=&quot;_19waq6b&quot;]/div[@class=&quot;c1yo0219 dir dir-ltr&quot;]/div[1]/div[@class=&quot;dir dir-ltr&quot;]/div[@class=&quot;giajdwt g14v8520 dir dir-ltr&quot;]/div[@class=&quot;c4mnd7m dir dir-ltr&quot;]/div[@class=&quot;c1l1h97y dir dir-ltr&quot;]/div[1]/div[1]/div[1]/div[@class=&quot;cy5jw6o  dir dir-ltr&quot;]/div[@class=&quot;mz543g6 dir dir-ltr&quot;]/div[@class=&quot;c14dgvke dir dir-ltr&quot;]/div[@class=&quot;cnjlbcx cp0pqp0 rztl681 dir dir-ltr&quot;]/div[@class=&quot;s1yvqyx7 dir dir-ltr&quot;]/div[@class=&quot;dir dir-ltr&quot;]/div[@class=&quot;awuxh4x dir dir-ltr&quot;]/div[@class=&quot;cw9aemg dir dir-ltr&quot;]/div[@class=&quot;c14whb16 dir dir-ltr&quot;]/a[@class=&quot;rfexzly dir dir-ltr&quot;]/div[@class=&quot;cjv59qb dir dir-ltr&quot;]/div[@class=&quot;_1h6n1zu&quot;]/picture[1]/img[@id=&quot;FMP-target&quot;]</value>
      <webElementGuid>39f7e3ef-0cc9-4624-a1f1-bfd62fadbefc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='FMP-target']</value>
      <webElementGuid>8e5350f6-f02f-4a81-a6ef-6b063b473362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='site-content']/div[2]/div[4]/div/div/div/div/div/div/div/div/div/div/div/div[2]/div/div/div/div/div/div/div/div[3]/div/div/div/div/a/div/div/picture/img</value>
      <webElementGuid>1986a0ff-a901-4ed4-9ca5-7ebd4c1f3756</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Image 1']</value>
      <webElementGuid>3b38c896-0a27-42ad-890e-d83046ba71d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//picture/img</value>
      <webElementGuid>899226ca-7ea4-4fda-9a08-5de997c4b476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@alt = 'Image 1' and @id = 'FMP-target' and @src = 'https://a0.muscache.com/im/pictures/af870499-6c81-4b77-b283-c861cc7c93ed.jpg?im_w=720']</value>
      <webElementGuid>f4866b02-d558-4cae-859c-27a2a85cfbc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
