<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ORDER_checkbox_design__sArRO</name>
   <tag></tag>
   <elementGuidId>80fd0088-7dab-4a49-84cd-6f9254ce90da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.checkbox_design__sArRO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[2]/div/div[2]/label/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>804440dc-2d80-4845-b7b3-91c4bcad8e67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox_design__sArRO</value>
      <webElementGuid>ef737395-2032-47e5-bb60-c49c59906f71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;dashboard_outbox__1-m91&quot;]/div[@class=&quot;dashboard_box__3yhj7&quot;]/div[@class=&quot;dashboard_filter__1u2Cj&quot;]/div[1]/div[@class=&quot;filter_outbox__1IMbW&quot;]/div[@class=&quot;filter_box__1bW3P&quot;]/div[@class=&quot;filter_content__Vyog7&quot;]/div[@class=&quot;filter_block__346dt&quot;]/div[@class=&quot;checkbox_outbox__1j2tl&quot;]/label[1]/div[@class=&quot;checkbox_design__sArRO&quot;]</value>
      <webElementGuid>dd4366f7-ba4d-4c8c-b13c-a3083a5b5090</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div/div/div/div/div[2]/div/div[2]/label/div</value>
      <webElementGuid>e2c42047-b8b9-4633-ba69-ea515cee3296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>8ca0a873-35cf-4bfa-843e-dfe5803de936</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
